#!/usr/bin/env python3
"""Generates src/shared/Visitors.luau: the 150 unique visitors in the Index.

Every visitor has a fixed rarity and a personality (archetype, see
PitchData.luau). Run from the project root: python3 tools/build_visitors.py
"""

import os

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "shared", "Visitors.luau")

# (rarity, archetype pool, names). A name can force its archetype with "Name|archetype".
TIERS = [
    ("common", ["tourist", "plumber", "dentist", "mom", "intern"], [
        "Gary Pennington", "Linda Inkwell", "Bob Clicker", "Sharon Staples", "Dave Doodle",
        "Karen Ballpoint", "Steve Scribble", "Pam Papers", "Tony Tipper", "Brenda Blot",
        "Hank Hardhat|plumber", "Doris Draft", "Kevin Cartridge", "Tina Tabs", "Mike Margins",
        "Sue Sticky", "Agent Joe Plainclothes|fbi", "Joyce Jotter", "Larry Ledger", "Nancy Notepad",
        "Ricky Refill", "Wendy Whiteout", "Carl Crayon", "Patty Post-It", "Earl Eraser",
        "Gina Glue", "Walter Wrench|plumber", "Rhonda Receipt", "Terry Tourist|tourist", "Molly Minivan|mom",
        "Doug Drainpipe|plumber", "Cindy Carpool|mom", "Barry Backpack|tourist", "Tammy Toothbrush|dentist", "Phil Filling|dentist",
        "Nora Nametag|intern", "Ron Rollerball", "Judy Journal", "Otis Overtime|intern", "Fiona Fanny-Pack|tourist",
    ]),
    ("rare", ["intern", "accountant", "dentist", "mom", "shoes", "tourist"], [
        "Chad Spreadsheet", "Brittany Bonds", "Trevor Tax-Return|accountant", "Megan Memo", "Jason Invoice",
        "Ashley Audit|accountant", "Kyle Quarterly", "Heather Hedge", "Derek Dividend", "Stacy Stapler",
        "Todd Timesheet", "Kimberly Keynote", "Brandon Budget", "Lauren Ledgerman", "Marcus Margin",
        "Jenna Jargon", "Eric Escrow", "Tiffany Tickers", "Scott Synergy", "Amber Assets",
        "Agent Wiretap Wendy|fbi", "Nicole Net-Worth", "Justin Just-In-Time", "Crystal Compliance|accountant", "Ryan Rollover",
        "Vanessa Venture", "Blake Bullpen", "Chelsea Cufflink|shoes", "Travis Trendline", "Monica Mergers",
        "Wade Wiretransfer", "Holly Holdings",
    ]),
    ("superrare", ["shoes", "bro", "accountant", "swiss", "intern"], [
        "Chip Leveraged", "Trip Tradewell", "Skip Stockley", "Biff Buyback", "Muffy Moneypenny",
        "Preston Portfolio", "Whitney Windfall", "Sterling Silverpen", "Blaine Bullmarket", "Tucker Trustfund",
        "Cassidy Commodity", "Brock Brokerage", "Paige Pinstripe", "Hunter Highyield", "Madison Avenue|shoes",
        "Colby Collateral", "Reese Reserve", "Parker Pennystock|bro", "Sloane Sellhigh", "Grant Goldmine",
        "Quinn Quantitative|accountant", "Remy Runup", "Dexter Derivative", "Harper Hedgefund|bro", "Knox Nasdaq",
        "Jett Junkbond",
    ]),
    ("epic", ["bro", "swiss", "oil", "crypto", "influencer", "rockstar"], [
        "Rex Rolex", "Lola Lamborghina|influencer", "Maximilian Moneybags", "Crypto Carl|crypto", "Nina NFT|crypto",
        "Diamond Hands Dan|crypto", "Moonboy Mo|crypto", "Yolanda Yachtley", "Rocco Rockstar|rockstar", "Sasha Superstar|rockstar",
        "Ivan Offshore|swiss", "Gustav Gnomeberg|swiss", "Pierre Portefeuille|swiss", "Tex Petrolski|oil", "Sheikh Shinypen|oil",
        "Influencer Izzy|influencer", "Blitz Bitcoin|crypto", "Vivian Vintage|influencer", "Duke Dividendsworth", "Marco Monaco",
    ]),
    ("mythic", ["duchess", "oil", "prince", "swiss", "rockstar", "crypto"], [
        "Lady Penelope Inkworth|duchess", "Baron Von Ballpoint|prince", "Prince Pennington III|prince", "Count Cashula|prince",
        "Countess Quill|duchess", "Sir Signsalot|prince", "Agent Pat Denpen|fbi", "Buck Barrels|oil",
        "Sultan of Stationery|oil", "Mama Montblank|duchess", "Rick Royalty|rockstar", "Satoshi Penamoto|crypto",
        "Dame Diamond Nib|duchess", "Archduke Autograph|prince",
    ]),
    ("legendary", ["bro"], [
        "Donnie Azpen|bro", "Mark Hannapen|bro", "Naomi Lapenglia|duchess", "Brad Napkinson|bro", "Aunt Emma Inkwell|duchess",
        "Mad Max Jolfort|accountant", "Jean-Jacques Pensaurel|swiss", "Captain Ted Tidewater|oil", "Chester Ming-Pen|bro",
        "Nicky Koskopen|bro",
    ]),
    ("exotic", ["prince"], [
        "The Golden Bull|oil", "Queen of the Quills|prince", "Space Baron Zorp|crypto", "The Invisible Hand|accountant",
        "The Fountain Pen of Youth|duchess", "Captain Compound Interest|accountant", "The Pen Pharaoh|prince",
    ]),
    ("ultra", ["wolf"], ["Beldan Jolfort|wolf"]),
]


def main():
    lines = [
        "-- GENERATED by tools/build_visitors.py. Edit that file, not this one.",
        "-- The 150 unique visitors of the Index. Each has a fixed rarity.",
        "",
        "local Visitors = {",
    ]
    count = 0
    for rarity, pool, names in TIERS:
        lines.append(f"\t-- {rarity}")
        for i, entry in enumerate(names):
            name, _, forced = entry.partition("|")
            archetype = forced or pool[i % len(pool)]
            count += 1
            safe = name.replace('"', '\\"')
            lines.append(f'\t{{ id = "v{count}", name = "{safe}", rarity = "{rarity}", archetype = "{archetype}" }},')
    lines += [
        "}",
        "",
        "Visitors.byId = {}",
        "Visitors.byRarity = {}",
        "for index, visitor in ipairs(Visitors) do",
        "\tvisitor.number = index",
        "\tVisitors.byId[visitor.id] = visitor",
        "\tVisitors.byRarity[visitor.rarity] = Visitors.byRarity[visitor.rarity] or {}",
        "\ttable.insert(Visitors.byRarity[visitor.rarity], visitor)",
        "end",
        "",
        "return Visitors",
        "",
    ]
    assert count == 150, count
    with open(OUT, "w") as f:
        f.write("\n".join(lines))
    print(f"Wrote {os.path.relpath(OUT)} with {count} visitors")


if __name__ == "__main__":
    main()
